version: '3'

services:
  elasticsearch:
    container_name: elasticsearch
    networks:
      - elastic
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300

  logstash:
    container_name: logstash
    networks:
      - elastic
    build:
      context: .
      dockerfile: Dockerfile.logstash
    volumes:
      - ./config-logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./pipeline-logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - 5044:5044
      - 50000:50000/tcp
      - 50000:50000/udp
      - 9600:9600
    restart: unless-stopped

  kibana:
    container_name: kibana
    networks:
      - elastic
    build:
      context: .
      dockerfile: Dockerfile.kibana
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    
  rabbitmq:
    container_name: rabbitmq
    networks:
      - elastic
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    depends_on:
      - elasticsearch
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    restart: unless-stopped

  prometheus:
    container_name: prometheus
    networks:
      - elastic
    build:
      context: .
      dockerfile: ./prometheus/Dockerfile.prometheus
    depends_on:
      - rabbitmq
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml

  alertmanager:
    container_name: alertmanager
    networks:
      - elastic
    build:
      context: .
      dockerfile: ./alertmanager/Dockerfile.alertmanager
    depends_on:
      - prometheus
    ports:
      - "9093:9093"
    restart: unless-stopped
    volumes:
      - "./alertmanager:/config"
    command: --config.file=/config/alertmanager.yml --log.level=debug

networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch: